import { describe, it, expect, vi, beforeEach } from 'vitest'
import { parseDNAFile, KEY_SNPS } from '@/lib/dna-parser'
import fs from 'fs'
import path from 'path'
import crypto from 'crypto'

// Sample data matching the actual sample file format
const SAMPLE_DNA_CONTENT = `# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024
#
# rsid\tchromosome\tposition\tgenotype
rs7903146\t10\t114758349\tCT
rs1801133\t1\t11856378\tCT
rs429358\t19\t45411941\tCT
rs9939609\t16\t53786615\tAT
rs4680\t22\t19951271\tAG
rs53576\t3\t8762685\tGG`

describe('DNA Analysis Integration', () => {
  it('should parse sample DNA file and match variants against KEY_SNPS', () => {
    const variants = parseDNAFile(SAMPLE_DNA_CONTENT)
    const matchedVariants = variants.filter(v => v.rsid in KEY_SNPS)

    // All 6 data lines have RSIDs that are in KEY_SNPS
    expect(matchedVariants.length).toBeGreaterThan(0)
    expect(matchedVariants.length).toBeLessThanOrEqual(variants.length)

    // Each matched variant should have corresponding KEY_SNPS metadata
    for (const variant of matchedVariants) {
      const snpData = KEY_SNPS[variant.rsid]
      expect(snpData).toBeDefined()
      expect(snpData.gene).toBeTruthy()
      expect(snpData.description).toBeTruthy()
    }
  })

  it('should produce a content-based hash for caching analysis results', () => {
    const hash1 = crypto.createHash('sha256').update(SAMPLE_DNA_CONTENT).digest('hex')
    const hash2 = crypto.createHash('sha256').update(SAMPLE_DNA_CONTENT).digest('hex')
    const differentHash = crypto.createHash('sha256').update('different content').digest('hex')

    // Same content should produce same hash
    expect(hash1).toBe(hash2)
    // Different content should produce different hash
    expect(hash1).not.toBe(differentHash)
    // Hash should be a valid hex string
    expect(hash1).toMatch(/^[a-f0-9]{64}$/)
  })

  it('should have sample-dna.txt available in public directory', () => {
    const publicSamplePath = path.resolve(process.cwd(), 'public/sample-dna.txt')
    expect(fs.existsSync(publicSamplePath)).toBe(true)

    const content = fs.readFileSync(publicSamplePath, 'utf-8')
    // Should contain valid DNA data (comment lines and tab-separated data)
    expect(content).toContain('# This data file generated by 23andMe')
    expect(content).toContain('rs1801133')
  })

  it('should have standalone output configured in next.config.ts', () => {
    const configPath = path.resolve(process.cwd(), 'next.config.ts')
    const configContent = fs.readFileSync(configPath, 'utf-8')

    expect(configContent).toContain("output: 'standalone'")
  })

  it('should have @anthropic-ai/sdk listed as a dependency', () => {
    const packageJsonPath = path.resolve(process.cwd(), 'package.json')
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'))

    expect(packageJson.dependencies).toHaveProperty('@anthropic-ai/sdk')
  })

  it('should enrich parsed variants with gene metadata from KEY_SNPS', () => {
    const variants = parseDNAFile(SAMPLE_DNA_CONTENT)

    // Build enriched results — this is the core integration logic
    const enriched = variants
      .filter(v => v.rsid in KEY_SNPS)
      .map(v => ({
        ...v,
        gene: KEY_SNPS[v.rsid].gene,
        description: KEY_SNPS[v.rsid].description,
      }))

    expect(enriched.length).toBeGreaterThan(0)

    // Verify enriched data has all expected fields
    for (const entry of enriched) {
      expect(entry).toHaveProperty('rsid')
      expect(entry).toHaveProperty('chromosome')
      expect(entry).toHaveProperty('position')
      expect(entry).toHaveProperty('genotype')
      expect(entry).toHaveProperty('gene')
      expect(entry).toHaveProperty('description')
    }

    // Spot check: rs7903146 should map to TCF7L2
    const tcf7l2 = enriched.find(e => e.rsid === 'rs7903146')
    expect(tcf7l2).toBeDefined()
    expect(tcf7l2!.gene).toBe('TCF7L2')
    expect(tcf7l2!.genotype).toBe('CT')
  })
})
