import { describe, it, expect } from 'vitest'
import { parseDNAFile, KEY_SNPS, type SNPVariant } from '@/lib/dna-parser'

describe('parseDNAFile', () => {
  it('should parse valid tab-separated DNA data lines into SNPVariant array', () => {
    const input = [
      '# comment line',
      'rs7903146\t10\t114758349\tCT',
      'rs1801133\t1\t11856378\tCT',
    ].join('\n')

    const result = parseDNAFile(input)

    expect(result).toHaveLength(2)
    expect(result[0]).toEqual({
      rsid: 'rs7903146',
      chromosome: '10',
      position: 114758349,
      genotype: 'CT',
    })
    expect(result[1]).toEqual({
      rsid: 'rs1801133',
      chromosome: '1',
      position: 11856378,
      genotype: 'CT',
    })
  })

  it('should skip all comment lines starting with #', () => {
    const input = [
      '# This data file generated by 23andMe',
      '#',
      '# Below is a tab-separated table of SNP information:',
      '# rsid\tchromosome\tposition\tgenotype',
      'rs429358\t19\t45411941\tCT',
    ].join('\n')

    const result = parseDNAFile(input)

    expect(result).toHaveLength(1)
    expect(result[0].rsid).toBe('rs429358')
  })

  it('should return empty array for empty input string', () => {
    const result = parseDNAFile('')
    expect(result).toEqual([])
  })

  it('should return empty array when input contains only comment lines', () => {
    const input = [
      '# comment 1',
      '# comment 2',
      '# comment 3',
    ].join('\n')

    const result = parseDNAFile(input)
    expect(result).toEqual([])
  })

  it('should correctly parse position as a number not a string', () => {
    const input = 'rs9939609\t16\t53786615\tAT'
    const result = parseDNAFile(input)

    expect(result[0].position).toBe(53786615)
    expect(typeof result[0].position).toBe('number')
  })

  it('should handle blank lines gracefully', () => {
    const input = [
      'rs429358\t19\t45411941\tCT',
      '',
      'rs7412\t19\t45412079\tCC',
      '   ',
    ].join('\n')

    const result = parseDNAFile(input)

    // Should only include valid data lines, skipping blank/whitespace lines
    const validEntries = result.filter(r => r.rsid && r.chromosome)
    expect(validEntries).toHaveLength(2)
  })

  it('should parse the full sample file and return all data rows', () => {
    // The sample file has 7 comment lines and 30 data rows
    const sampleContent = `# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024
#
# This file contains raw genotype data, including data that is not used in 23andMe reports.
# This data has been checked for quality, but is not suitable for medical diagnoses.
#
# Below is a tab-separated table of SNP information:
# rsid\tchromosome\tposition\tgenotype
rsid7903146\t10\t114758349\tCT
rs1801133\t1\t11856378\tCT
rs429358\t19\t45411941\tCT
rs7412\t19\t45412079\tCC
rs1801394\t5\t7870973\tAG
rs72552267\t10\t96741053\tAG
rs1695\t11\t67352689\tAA
rs1800562\t6\t26093141\tGG
rs1801282\t3\t12393125\tCC
rs9939609\t16\t53786615\tAT
rs1815739\t11\t66560624\tCT
rs4680\t22\t19951271\tAG
rs6265\t11\t27679916\tCT
rs4988235\t2\t136608646\tCT
rs12913832\t15\t28365618\tAG
rs1800497\t11\t113270828\tAG
rs334\t11\t5246696\tAT
rs53576\t3\t8762685\tGG
rs2187668\t6\t32713862\tTC
rs1049353\t1\t53246555\tAG
rs12255372\t10\t114758349\tTG
rs7901695\t10\t114808179\tCC
rs5219\t11\t17388025\tCT
rs1799853\t10\t96522463\tCT
rs1057910\t10\t96613052\tAC
rs2740574\t7\t87138645\tAC
rs776746\t7\t99270424\tAG
rs1045642\t7\t87138562\tAG
rs4244285\t10\t96522463\tGA
rs4986893\t10\t96613052\tGG`

    const result = parseDNAFile(sampleContent)
    expect(result).toHaveLength(30)
  })

  it('should return SNPVariant objects with correct shape', () => {
    const input = 'rs53576\t3\t8762685\tGG'
    const result = parseDNAFile(input)

    expect(result[0]).toHaveProperty('rsid')
    expect(result[0]).toHaveProperty('chromosome')
    expect(result[0]).toHaveProperty('position')
    expect(result[0]).toHaveProperty('genotype')
  })
})

describe('KEY_SNPS', () => {
  it('should contain all 14 required RSID entries', () => {
    const requiredRSIDs = [
      'rs7903146', 'rs1801133', 'rs429358', 'rs7412',
      'rs9939609', 'rs1815739', 'rs4680', 'rs6265',
      'rs4988235', 'rs12913832', 'rs1800497', 'rs53576',
      'rs334', 'rs1800562',
    ]

    for (const rsid of requiredRSIDs) {
      expect(KEY_SNPS).toHaveProperty(rsid)
    }
    expect(Object.keys(KEY_SNPS)).toHaveLength(14)
  })

  it('should have gene and description for every KEY_SNP entry', () => {
    for (const [rsid, data] of Object.entries(KEY_SNPS)) {
      expect(data.gene, `${rsid} missing gene`).toBeTruthy()
      expect(data.description, `${rsid} missing description`).toBeTruthy()
    }
  })

  it('should map correct genes to specific RSIDs', () => {
    expect(KEY_SNPS['rs7903146'].gene).toBe('TCF7L2')
    expect(KEY_SNPS['rs1801133'].gene).toBe('MTHFR C677T')
    expect(KEY_SNPS['rs429358'].gene).toBe('APOE')
    expect(KEY_SNPS['rs9939609'].gene).toBe('FTO')
    expect(KEY_SNPS['rs4988235'].gene).toBe('LCT')
    expect(KEY_SNPS['rs334'].gene).toBe('HBB')
  })
})
